# 定義階段
stages:
  - check
  - build
  - deploy


default:
  image: node:18
  cache:  # Cache modules in between jobs
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline

# 檢查階段
check:
  stage: check
  script:
    - echo "執行格式檢查..."
    - npx prettier --check "**/*.{js,vue}" 
    - echo "執行代碼規則檢查..."
    - npm run lint

# 構建階段
build:
  stage: build
  needs:
    - check
  script:
    - echo "構建應用..."
    - npm run build
  artifacts:
    paths:
      - public/

# 部署到 GitLab Pages 的工作
pages:
  stage: deploy
  needs:
    - build
  script:
    - echo "GitLab Pages 域名: $CI_PAGES_DOMAIN"
    - echo "GitLab Pages URL: $CI_PAGES_URL"
    - echo "項目 URL: $CI_PROJECT_URL"
    # 確保 public 目錄存在且包含 index.html
    - ls -la public/
    - if [ ! -f "public/index.html" ]; then echo "Error: public/index.html not found!"; exit 1; fi
  artifacts:
    paths:
      - public/
  only:
    - main
