# 定義階段
stages:
  - check
  - build
  - deploy


default:
  image: node:18
  cache:  # Cache modules in between jobs
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline

# 檢查階段
check:
  stage: check
  needs:
    - setup
  script:
    - echo "執行格式檢查..."
    - npm prettier --check "src/**/*.{js,vue}"
    - echo "執行代碼規則檢查..."
    - npm run lint

# 構建階段
build:
  stage: build
  needs:
    - check
  script:
    - echo "構建應用..."
    - npm build
  artifacts:
    paths:
      - public/

# 部署到 GitLab Pages 的工作
pages:
  stage: deploy
  needs:
    - build
  script:
    - echo "部署到 GitLab Pages..."
  artifacts:
    paths:
      - public/
  only:
    - main
