# Node.js 版本
image: node:18

# 定義階段
stages:
  - check
  - build
  - deploy

# 全局快取配置
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
  policy: pull-push

# 規則檢查
check:
  stage: check
  script:
    - npm ci # 使用 ci(clean install) 而不是 install 以確保一致性安裝
    - npx prettier --check "**/*.{js,vue}"
    - npm run lint
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: pull-push

# 構建階段的工作
build:
  stage: build
  needs:
    - check
  script:
    - npm run build
  artifacts:
    paths:
      - public/ # Vite 構建後的輸出目錄
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: pull

# 部署到 GitLab Pages 的工作
pages:
  stage: deploy
  script:
    - echo "部署到 GitLab Pages"
  artifacts:
    paths:
      - public/ # GitLab Pages 需要 public 目錄
  only:
    - main # 只在主分支執行部署
  needs:
    - build # 依賴於構建工作
